version: '3.8'

services:
  news-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - VITE_NEWS_API_KEY=${VITE_NEWS_API_KEY}
      - VITE_NYT_API_KEY=${VITE_NYT_API_KEY}
      - VITE_GUARDIAN_API_KEY=${VITE_GUARDIAN_API_KEY}
